apply plugin: "java-library"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

sourceSets.main.java.srcDirs = [ "src/", "gen/" ]


eclipse.project {
    name = appName + "-core"
}

compileJava {
    options.release = 8
}
java.targetCompatibility = JavaVersion.VERSION_1_8